### ISSUE TITLE
Update FuxiCTR hyperlink

### ISSUE THREAD

**Issue by zhujiem** [ACMRecSys/recsys-evaluation-frameworks#3]
The FuxiCTR project has been moved from https://github.com/xue-pai/FuxiCTR to https://github.com/reczoo/FuxiCTR . Could you please help update the hyperlink in the README file? Thanks!

**Comment by alansaid** [comment]
Closed in https://github.com/ACMRecSys/recsys-evaluation-frameworks/commit/5024281db30be88d30b697d28eba0e41d383dd15
